package v1_18_0

import "github.com/sandertv/gophertunnel/minecraft/protocol/packet"

var packetMarshals = map[uint32]packetMarshal{
	packet.IDActorEvent:                        marshalActorEvent,
	packet.IDAddActor:                          marshalAddActor,
	packet.IDAddPlayer:                         marshalAddPlayer,
	packet.IDAddVolumeEntity:                   marshalAddVolumeEntity,
	packet.IDAnimate:                           marshalAnimate,
	packet.IDBiomeDefinitionList:               marshalBiomeDefinitionList,
	packet.IDBlockActorData:                    marshalBlockActorData,
	packet.IDBossEvent:                         marshalBossEvent,
	packet.IDAvailableCommands:                 marshalAvailableCommands,
	packet.IDChangeDimension:                   marshalChangeDimension,
	packet.IDClientBoundDebugRenderer:          marshalClientBoundDebugRenderer,
	packet.IDClientBoundMapItemData:            marshalClientBoundMapItemData,
	packet.IDCommandRequest:                    marshalCommandRequest,
	packet.IDCommandBlockUpdate:                marshalCommandBlockUpdate,
	packet.IDCommandOutput:                     marshalCommandOutput,
	packet.IDContainerClose:                    marshalContainerClose,
	packet.IDContainerOpen:                     marshalContainerOpen,
	packet.IDCorrectPlayerMovePrediction:       marshalCorrectPlayerMovePrediction,
	packet.IDCraftingData:                      marshalCraftingDataV475,
	packet.IDCreativeContent:                   marshalCreativeContent,
	packet.IDDisconnect:                        marshalDisconnect,
	packet.IDEmote:                             marshalEmote,
	packet.IDInteract:                          marshalInteract,
	packet.IDInventoryContent:                  marshalInventoryContent,
	packet.IDInventorySlot:                     marshalInventorySlot,
	packet.IDInventoryTransaction:              marshalInventoryTransactionPacket,
	packet.IDItemStackRequest:                  marshalItemStackRequestPacket,
	packet.IDItemStackResponse:                 marshalItemStackResponsePacket,
	packet.IDLecternUpdate:                     marshalLecternUpdate,
	packet.IDLevelSoundEvent:                   marshalLevelSoundEvent,
	packet.IDLevelChunk:                        marshalLevelChunk,
	packet.IDMapCreateLockedCopy:               marshalMapCreateLockedCopy,
	packet.IDMapInfoRequest:                    marshalMapInfoRequest,
	packet.IDMobArmourEquipment:                marshalMobArmourEquipment,
	packet.IDMobEffect:                         marshalMobEffect,
	packet.IDMobEquipment:                      marshalMobEquipment,
	packet.IDModalFormResponse:                 marshalModalFormResponse,
	packet.IDNetworkChunkPublisherUpdate:       marshalNetworkChunkPublisherUpdate,
	packet.IDNetworkSettings:                   marshalNetworkSettings,
	packet.IDOnScreenTextureAnimation:          marshalOnScreenTextureAnimation,
	packet.IDPlaySound:                         marshalPlaySound,
	packet.IDPlayerAction:                      marshalPlayerAction,
	packet.IDPlayerArmourDamage:                marshalPlayerArmourDamage,
	packet.IDPlayerAuthInput:                   marshalPlayerAuthInput,
	packet.IDPlayerList:                        marshalPlayerList,
	packet.IDPlayerSkin:                        marshalPlayerSkin,
	packet.IDPositionTrackingDBServerBroadcast: marshalPositionTrackingDBServerBroadcast,
	packet.IDRemoveVolumeEntity:                marshalRemoveVolumeEntity,
	packet.IDRequestChunkRadius:                marshalRequestChunkRadius,
	packet.IDResourcePackClientResponse:        marshalResourcePackClientResponse,
	packet.IDResourcePacksInfo:                 marshalResourcePacksInfo,
	packet.IDResourcePackStack:                 marshalResourcePackStack,
	packet.IDSetActorData:                      marshalSetActorData,
	packet.IDSetActorLink:                      marshalSetActorLink,
	packet.IDSetActorMotion:                    marshalSetActorMotion,
	packet.IDSetTitle:                          marshalSetTitle,
	packet.IDShowStoreOffer:                    marshalShowStoreOffer,
	packet.IDSpawnParticleEffect:               marshalSpawnParticleEffect,
	packet.IDStructureBlockUpdate:              marshalStructureBlockUpdate,
	packet.IDStructureTemplateDataRequest:      marshalStructureTemplateDataRequest,
	packet.IDStartGame:                         marshalStartGame,
	packet.IDStopSound:                         marshalStopSound,
	packet.IDSubChunk:                          marshalSubChunk,
	packet.IDSubChunkRequest:                   marshalSubChunkRequest,
	packet.IDText:                              marshalText,
	packet.IDTransfer:                          marshalTransfer,
	packet.IDUpdateAttributes:                  marshalUpdateAttributes,
	packet.IDUpdateBlock:                       marshalUpdateBlock,
	packet.IDUpdateBlockSynced:                 marshalUpdateBlockSynced,
	packet.IDUpdatePlayerGameType:              marshalUpdatePlayerGameType,
}

const maxLegacyPacketID uint32 = 175

var droppedPacketIDs = map[uint32]struct{}{
	packet.IDItemRegistry: {},
}
