package v1_26_30

import "github.com/sandertv/gophertunnel/minecraft/protocol/packet"

var packetMarshals = map[uint32]packetMarshal{
	packet.IDAddPlayer:                    marshalAddPlayer,
	packet.IDAnvilDamage:                  marshalAnvilDamage,
	packet.IDAvailableCommands:            marshalAvailableCommands,
	packet.IDClientBoundMapItemData:       marshalClientBoundMapItemData,
	packet.IDClientMovementPredictionSync: marshalClientMovementPredictionSync,
	packet.IDClientboundUpdateSoundData:   marshalClientboundUpdateSoundData,
	packet.IDClientCheatAbility:           marshalClientCheatAbility,
	packet.IDCraftingData:                 marshalCraftingData,
	packet.IDCreativeContent:              marshalCreativeContent,
	packet.IDDimensionData:                marshalDimensionData,
	packet.IDHurtArmour:                   marshalHurtArmour,
	packet.IDInventoryContent:             marshalInventoryContent,
	packet.IDInventorySlot:                marshalInventorySlot,
	packet.IDInventoryTransaction:         marshalInventoryTransactionPacket,
	packet.IDItemStackResponse:            marshalItemStackResponsePacket,
	packet.IDLevelChunk:                   marshalLevelChunk,
	packet.IDMobArmourEquipment:           marshalMobArmourEquipment,
	packet.IDMobEquipment:                 marshalMobEquipment,
	packet.IDMoveActorDelta:               marshalMoveActorDelta,
	packet.IDMovePlayer:                   marshalMovePlayer,
	packet.IDPlaySound:                    marshalPlaySound,
	packet.IDPlayerAuthInput:              marshalPlayerAuthInput,
	packet.IDPlayerList:                   marshalPlayerList,
	packet.IDPlayerLocation:               marshalPlayerLocation,
	packet.IDPlayerSkin:                   marshalPlayerSkin,
	packet.IDPlayerUpdateEntityOverrides:  marshalPlayerUpdateEntityOverrides,
	packet.IDResourcePackClientResponse:   marshalResourcePackClientResponse,
	packet.IDResourcePacksInfo:            marshalResourcePacksInfo,
	packet.IDServerBoundDiagnostics:       marshalServerBoundDiagnostics,
	packet.IDSetScore:                     marshalSetScore,
	packet.IDSetScoreboardIdentity:        marshalSetScoreboardIdentity,
	packet.IDStartGame:                    marshalStartGame,
	packet.IDStructureBlockUpdate:         marshalStructureBlockUpdate,
	packet.IDSubChunk:                     marshalSubChunk,
	packet.IDSubChunkRequest:              marshalSubChunkRequest,
	packet.IDTransfer:                     marshalTransfer,
	packet.IDUpdateAbilities:              marshalUpdateAbilities,
}
