package v1_21_50

import (
	"github.com/go-gl/mathgl/mgl32"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
	"github.com/sandertv/gophertunnel/minecraft/protocol/packet"
)

// soundEvents827 is generated from the final protocol-766 gophertunnel
// snapshot and the later numeric-to-string transition at 6353c49.
var soundEvents827 = [...]string{
	"item.use.on",                      // 0 SoundEventItemUseOn
	"hit",                              // 1 SoundEventHit
	"step",                             // 2 SoundEventStep
	"fly",                              // 3 SoundEventFly
	"jump",                             // 4 SoundEventJump
	"break",                            // 5 SoundEventBreak
	"place",                            // 6 SoundEventPlace
	"heavy.step",                       // 7 SoundEventHeavyStep
	"gallop",                           // 8 SoundEventGallop
	"fall",                             // 9 SoundEventFall
	"ambient",                          // 10 SoundEventAmbient
	"ambient.baby",                     // 11 SoundEventAmbientBaby
	"ambient.in.water",                 // 12 SoundEventAmbientInWater
	"breathe",                          // 13 SoundEventBreathe
	"death",                            // 14 SoundEventDeath
	"death.in.water",                   // 15 SoundEventDeathInWater
	"death.to.zombie",                  // 16 SoundEventDeathToZombie
	"hurt",                             // 17 SoundEventHurt
	"hurt.in.water",                    // 18 SoundEventHurtInWater
	"mad",                              // 19 SoundEventMad
	"boost",                            // 20 SoundEventBoost
	"bow",                              // 21 SoundEventBow
	"squish.big",                       // 22 SoundEventSquishBig
	"squish.small",                     // 23 SoundEventSquishSmall
	"fall.big",                         // 24 SoundEventFallBig
	"fall.small",                       // 25 SoundEventFallSmall
	"splash",                           // 26 SoundEventSplash
	"fizz",                             // 27 SoundEventFizz
	"flap",                             // 28 SoundEventFlap
	"swim",                             // 29 SoundEventSwim
	"drink",                            // 30 SoundEventDrink
	"eat",                              // 31 SoundEventEat
	"takeoff",                          // 32 SoundEventTakeoff
	"shake",                            // 33 SoundEventShake
	"plop",                             // 34 SoundEventPlop
	"land",                             // 35 SoundEventLand
	"saddle",                           // 36 SoundEventSaddle
	"armor",                            // 37 SoundEventArmor
	"mob.armor_stand.place",            // 38 SoundEventArmorPlace
	"add.chest",                        // 39 SoundEventAddChest
	"throw",                            // 40 SoundEventThrow
	"attack",                           // 41 SoundEventAttack
	"attack.nodamage",                  // 42 SoundEventAttackNoDamage
	"attack.strong",                    // 43 SoundEventAttackStrong
	"warn",                             // 44 SoundEventWarn
	"shear",                            // 45 SoundEventShear
	"milk",                             // 46 SoundEventMilk
	"thunder",                          // 47 SoundEventThunder
	"explode",                          // 48 SoundEventExplode
	"fire",                             // 49 SoundEventFire
	"ignite",                           // 50 SoundEventIgnite
	"fuse",                             // 51 SoundEventFuse
	"stare",                            // 52 SoundEventStare
	"spawn",                            // 53 SoundEventSpawn
	"shoot",                            // 54 SoundEventShoot
	"break.block",                      // 55 SoundEventBreakBlock
	"launch",                           // 56 SoundEventLaunch
	"blast",                            // 57 SoundEventBlast
	"large.blast",                      // 58 SoundEventLargeBlast
	"twinkle",                          // 59 SoundEventTwinkle
	"remedy",                           // 60 SoundEventRemedy
	"unfect",                           // 61 SoundEventUnfect
	"levelup",                          // 62 SoundEventLevelUp
	"bow.hit",                          // 63 SoundEventBowHit
	"bullet.hit",                       // 64 SoundEventBulletHit
	"extinguish.fire",                  // 65 SoundEventExtinguishFire
	"item.fizz",                        // 66 SoundEventItemFizz
	"chest.open",                       // 67 SoundEventChestOpen
	"chest.closed",                     // 68 SoundEventChestClosed
	"shulkerbox.open",                  // 69 SoundEventShulkerBoxOpen
	"shulkerbox.closed",                // 70 SoundEventShulkerBoxClosed
	"enderchest.open",                  // 71 SoundEventEnderChestOpen
	"enderchest.closed",                // 72 SoundEventEnderChestClosed
	"power.on",                         // 73 SoundEventPowerOn
	"power.off",                        // 74 SoundEventPowerOff
	"attach",                           // 75 SoundEventAttach
	"detach",                           // 76 SoundEventDetach
	"deny",                             // 77 SoundEventDeny
	"tripod",                           // 78 SoundEventTripod
	"pop",                              // 79 SoundEventPop
	"drop.slot",                        // 80 SoundEventDropSlot
	"note",                             // 81 SoundEventNote
	"thorns",                           // 82 SoundEventThorns
	"piston.in",                        // 83 SoundEventPistonIn
	"piston.out",                       // 84 SoundEventPistonOut
	"portal",                           // 85 SoundEventPortal
	"water",                            // 86 SoundEventWater
	"lava.pop",                         // 87 SoundEventLavaPop
	"lava",                             // 88 SoundEventLava
	"burp",                             // 89 SoundEventBurp
	"bucket.fill.water",                // 90 SoundEventBucketFillWater
	"bucket.fill.lava",                 // 91 SoundEventBucketFillLava
	"bucket.empty.water",               // 92 SoundEventBucketEmptyWater
	"bucket.empty.lava",                // 93 SoundEventBucketEmptyLava
	"armor.equip_chain",                // 94 SoundEventEquipChain
	"armor.equip_diamond",              // 95 SoundEventEquipDiamond
	"armor.equip_generic",              // 96 SoundEventEquipGeneric
	"armor.equip_gold",                 // 97 SoundEventEquipGold
	"armor.equip_iron",                 // 98 SoundEventEquipIron
	"armor.equip_leather",              // 99 SoundEventEquipLeather
	"armor.equip_elytra",               // 100 SoundEventEquipElytra
	"record.13",                        // 101 SoundEventRecord13
	"record.cat",                       // 102 SoundEventRecordCat
	"record.blocks",                    // 103 SoundEventRecordBlocks
	"record.chirp",                     // 104 SoundEventRecordChirp
	"record.far",                       // 105 SoundEventRecordFar
	"record.mall",                      // 106 SoundEventRecordMall
	"record.mellohi",                   // 107 SoundEventRecordMellohi
	"record.stal",                      // 108 SoundEventRecordStal
	"record.strad",                     // 109 SoundEventRecordStrad
	"record.ward",                      // 110 SoundEventRecordWard
	"record.11",                        // 111 SoundEventRecord11
	"record.wait",                      // 112 SoundEventRecordWait
	"record.null",                      // 113 SoundEventRecordNull
	"flop",                             // 114 SoundEventFlop
	"elderguardian.curse",              // 115 SoundEventGuardianCurse
	"mob.warning",                      // 116 SoundEventMobWarning
	"mob.warning.baby",                 // 117 SoundEventMobWarningBaby
	"teleport",                         // 118 SoundEventTeleport
	"shulker.open",                     // 119 SoundEventShulkerOpen
	"shulker.close",                    // 120 SoundEventShulkerClose
	"haggle",                           // 121 SoundEventHaggle
	"haggle.yes",                       // 122 SoundEventHaggleYes
	"haggle.no",                        // 123 SoundEventHaggleNo
	"haggle.idle",                      // 124 SoundEventHaggleIdle
	"chorusgrow",                       // 125 SoundEventChorusGrow
	"chorusdeath",                      // 126 SoundEventChorusDeath
	"glass",                            // 127 SoundEventGlass
	"potion.brewed",                    // 128 SoundEventPotionBrewed
	"cast.spell",                       // 129 SoundEventCastSpell
	"prepare.attack",                   // 130 SoundEventPrepareAttackSpell
	"prepare.summon",                   // 131 SoundEventPrepareSummon
	"prepare.wololo",                   // 132 SoundEventPrepareWololo
	"fang",                             // 133 SoundEventFang
	"charge",                           // 134 SoundEventCharge
	"camera.take_picture",              // 135 SoundEventTakePicture
	"leashknot.place",                  // 136 SoundEventPlaceLeashKnot
	"leashknot.break",                  // 137 SoundEventBreakLeashKnot
	"growl",                            // 138 SoundEventAmbientGrowl
	"whine",                            // 139 SoundEventAmbientWhine
	"pant",                             // 140 SoundEventAmbientPant
	"purr",                             // 141 SoundEventAmbientPurr
	"purreow",                          // 142 SoundEventAmbientPurreow
	"death.min.volume",                 // 143 SoundEventDeathMinVolume
	"death.mid.volume",                 // 144 SoundEventDeathMidVolume
	"imitate.blaze",                    // 145 SoundEventImitateBlaze
	"imitate.cave_spider",              // 146 SoundEventImitateCaveSpider
	"imitate.creeper",                  // 147 SoundEventImitateCreeper
	"imitate.elder_guardian",           // 148 SoundEventImitateElderGuardian
	"imitate.ender_dragon",             // 149 SoundEventImitateEnderDragon
	"imitate.enderman",                 // 150 SoundEventImitateEnderman
	"imitate.endermite",                // 151 SoundEventImitateEndermite
	"imitate.evocation_illager",        // 152 SoundEventImitateEvocationIllager
	"imitate.ghast",                    // 153 SoundEventImitateGhast
	"imitate.husk",                     // 154 SoundEventImitateHusk
	"imitate.illusion_illager",         // 155 SoundEventImitateIllusionIllager
	"imitate.magma_cube",               // 156 SoundEventImitateMagmaCube
	"imitate.polar_bear",               // 157 SoundEventImitatePolarBear
	"imitate.shulker",                  // 158 SoundEventImitateShulker
	"imitate.silverfish",               // 159 SoundEventImitateSilverfish
	"imitate.skeleton",                 // 160 SoundEventImitateSkeleton
	"imitate.slime",                    // 161 SoundEventImitateSlime
	"imitate.spider",                   // 162 SoundEventImitateSpider
	"imitate.stray",                    // 163 SoundEventImitateStray
	"imitate.vex",                      // 164 SoundEventImitateVex
	"imitate.vindication_illager",      // 165 SoundEventImitateVindicationIllager
	"imitate.witch",                    // 166 SoundEventImitateWitch
	"imitate.wither",                   // 167 SoundEventImitateWither
	"imitate.wither_skeleton",          // 168 SoundEventImitateWitherSkeleton
	"imitate.wolf",                     // 169 SoundEventImitateWolf
	"imitate.zombie",                   // 170 SoundEventImitateZombie
	"imitate.zombie_pigman",            // 171 SoundEventImitateZombiePigman
	"imitate.zombie_villager",          // 172 SoundEventImitateZombieVillager
	"block.end_portal_frame.fill",      // 173 SoundEventEnderEyePlaced
	"block.end_portal.spawn",           // 174 SoundEventEndPortalCreated
	"random.anvil_use",                 // 175 SoundEventAnvilUse
	"bottle.dragonbreath",              // 176 SoundEventBottleDragonBreath
	"portal.travel",                    // 177 SoundEventPortalTravel
	"item.trident.hit",                 // 178 SoundEventTridentHit
	"item.trident.return",              // 179 SoundEventTridentReturn
	"item.trident.riptide_1",           // 180 SoundEventTridentRiptide1
	"item.trident.riptide_2",           // 181 SoundEventTridentRiptide2
	"item.trident.riptide_3",           // 182 SoundEventTridentRiptide3
	"item.trident.throw",               // 183 SoundEventTridentThrow
	"item.trident.thunder",             // 184 SoundEventTridentThunder
	"item.trident.hit_ground",          // 185 SoundEventTridentHitGround
	"default",                          // 186 SoundEventDefault
	"block.fletching_table.use",        // 187 SoundEventFletchingTableUse
	"elemconstruct.open",               // 188 SoundEventElemConstructOpen
	"icebomb.hit",                      // 189 SoundEventIceBombHit
	"balloonpop",                       // 190 SoundEventBalloonPop
	"lt.reaction.icebomb",              // 191 SoundEventLtReactionIceBomb
	"lt.reaction.bleach",               // 192 SoundEventLtReactionBleach
	"lt.reaction.epaste",               // 193 SoundEventLtReactionElephantToothpaste
	"lt.reaction.epaste2",              // 194 SoundEventLtReactionElephantToothpaste2
	"lt.reaction.glow_stick",           // 195 SoundEventLtReactionGlowStick
	"lt.reaction.glow_stick2",          // 196 SoundEventLtReactionGlowStick2
	"lt.reaction.luminol",              // 197 SoundEventLtReactionLuminol
	"lt.reaction.salt",                 // 198 SoundEventLtReactionSalt
	"lt.reaction.fertilizer",           // 199 SoundEventLtReactionFertilizer
	"lt.reaction.fireball",             // 200 SoundEventLtReactionFireball
	"lt.reaction.mgsalt",               // 201 SoundEventLtReactionMagnesiumSalt
	"lt.reaction.miscfire",             // 202 SoundEventLtReactionMiscFire
	"lt.reaction.fire",                 // 203 SoundEventLtReactionFire
	"lt.reaction.miscexplosion",        // 204 SoundEventLtReactionMiscExplosion
	"lt.reaction.miscmystical",         // 205 SoundEventLtReactionMiscMystical
	"lt.reaction.miscmystical2",        // 206 SoundEventLtReactionMiscMystical2
	"lt.reaction.product",              // 207 SoundEventLtReactionProduct
	"sparkler.use",                     // 208 SoundEventSparklerUse
	"glowstick.use",                    // 209 SoundEventGlowStickUse
	"sparkler.active",                  // 210 SoundEventSparklerActive
	"convert_to_drowned",               // 211 SoundEventConvertToDrowned
	"bucket.fill.fish",                 // 212 SoundEventBucketFillFish
	"bucket.empty.fish",                // 213 SoundEventBucketEmptyFish
	"bubble.up",                        // 214 SoundEventBubbleColumnUpwards
	"bubble.down",                      // 215 SoundEventBubbleColumnDownwards
	"bubble.pop",                       // 216 SoundEventBubblePop
	"bubble.upinside",                  // 217 SoundEventBubbleUpInside
	"bubble.downinside",                // 218 SoundEventBubbleDownInside
	"hurt.baby",                        // 219 SoundEventHurtBaby
	"death.baby",                       // 220 SoundEventDeathBaby
	"step.baby",                        // 221 SoundEventStepBaby
	"spawn.baby",                       // 222 SoundEventSpawnBaby
	"born",                             // 223 SoundEventBorn
	"block.turtle_egg.break",           // 224 SoundEventTurtleEggBreak
	"block.turtle_egg.crack",           // 225 SoundEventTurtleEggCrack
	"block.turtle_egg.hatch",           // 226 SoundEventTurtleEggHatched
	"lay_egg",                          // 227 SoundEventLayEgg
	"block.turtle_egg.attack",          // 228 SoundEventTurtleEggAttacked
	"beacon.activate",                  // 229 SoundEventBeaconActivate
	"beacon.ambient",                   // 230 SoundEventBeaconAmbient
	"beacon.deactivate",                // 231 SoundEventBeaconDeactivate
	"beacon.power",                     // 232 SoundEventBeaconPower
	"conduit.activate",                 // 233 SoundEventConduitActivate
	"conduit.ambient",                  // 234 SoundEventConduitAmbient
	"conduit.attack",                   // 235 SoundEventConduitAttack
	"conduit.deactivate",               // 236 SoundEventConduitDeactivate
	"conduit.short",                    // 237 SoundEventConduitShort
	"swoop",                            // 238 SoundEventSwoop
	"block.bamboo_sapling.place",       // 239 SoundEventBambooSaplingPlace
	"presneeze",                        // 240 SoundEventPreSneeze
	"sneeze",                           // 241 SoundEventSneeze
	"ambient.tame",                     // 242 SoundEventAmbientTame
	"scared",                           // 243 SoundEventScared
	"block.scaffolding.climb",          // 244 SoundEventScaffoldingClimb
	"crossbow.loading.start",           // 245 SoundEventCrossbowLoadingStart
	"crossbow.loading.middle",          // 246 SoundEventCrossbowLoadingMiddle
	"crossbow.loading.end",             // 247 SoundEventCrossbowLoadingEnd
	"crossbow.shoot",                   // 248 SoundEventCrossbowShoot
	"crossbow.quick_charge.start",      // 249 SoundEventCrossbowQuickChargeStart
	"crossbow.quick_charge.middle",     // 250 SoundEventCrossbowQuickChargeMiddle
	"crossbow.quick_charge.end",        // 251 SoundEventCrossbowQuickChargeEnd
	"ambient.aggressive",               // 252 SoundEventAmbientAggressive
	"ambient.worried",                  // 253 SoundEventAmbientWorried
	"cant_breed",                       // 254 SoundEventCantBreed
	"item.shield.block",                // 255 SoundEventShieldBlock
	"item.book.put",                    // 256 SoundEventLecternBookPlace
	"block.grindstone.use",             // 257 SoundEventGrindstoneUse
	"block.bell.hit",                   // 258 SoundEventBell
	"block.campfire.crackle",           // 259 SoundEventCampfireCrackle
	"roar",                             // 260 SoundEventRoar
	"stun",                             // 261 SoundEventStun
	"block.sweet_berry_bush.hurt",      // 262 SoundEventSweetBerryBushHurt
	"block.sweet_berry_bush.pick",      // 263 SoundEventSweetBerryBushPick
	"block.cartography_table.use",      // 264 SoundEventCartographyTableUse
	"block.stonecutter.use",            // 265 SoundEventStonecutterUse
	"block.composter.empty",            // 266 SoundEventComposterEmpty
	"block.composter.fill",             // 267 SoundEventComposterFill
	"block.composter.fill_success",     // 268 SoundEventComposterFillLayer
	"block.composter.ready",            // 269 SoundEventComposterReady
	"block.barrel.open",                // 270 SoundEventBarrelOpen
	"block.barrel.close",               // 271 SoundEventBarrelClose
	"raid.horn",                        // 272 SoundEventRaidHorn
	"block.loom.use",                   // 273 SoundEventLoomUse
	"ambient.in.raid",                  // 274 SoundEventAmbientInRaid
	"ui.cartography_table.take_result", // 275 SoundEventUicartographyTableUse
	"ui.stonecutter.take_result",       // 276 SoundEventUistonecutterUse
	"ui.loom.take_result",              // 277 SoundEventUiloomUse
	"block.smoker.smoke",               // 278 SoundEventSmokerUse
	"block.blastfurnace.fire_crackle",  // 279 SoundEventBlastFurnaceUse
	"block.smithing_table.use",         // 280 SoundEventSmithingTableUse
	"screech",                          // 281 SoundEventScreech
	"sleep",                            // 282 SoundEventSleep
	"block.furnace.lit",                // 283 SoundEventFurnaceUse
	"convert_mooshroom",                // 284 SoundEventMooshroomConvert
	"milk_suspiciously",                // 285 SoundEventMilkSuspiciously
	"celebrate",                        // 286 SoundEventCelebrate
	"jump.prevent",                     // 287 SoundEventJumpPrevent
	"ambient.pollinate",                // 288 SoundEventAmbientPollinate
	"block.beehive.drip",               // 289 SoundEventBeehiveDrip
	"block.beehive.enter",              // 290 SoundEventBeehiveEnter
	"block.beehive.exit",               // 291 SoundEventBeehiveExit
	"block.beehive.work",               // 292 SoundEventBeehiveWork
	"block.beehive.shear",              // 293 SoundEventBeehiveShear
	"drink.honey",                      // 294 SoundEventHoneybottleDrink
	"ambient.cave",                     // 295 SoundEventAmbientCave
	"retreat",                          // 296 SoundEventRetreat
	"converted_to_zombified",           // 297 SoundEventConvertToZombified
	"admire",                           // 298 SoundEventAdmire
	"step_lava",                        // 299 SoundEventStepLava
	"tempt",                            // 300 SoundEventTempt
	"panic",                            // 301 SoundEventPanic
	"angry",                            // 302 SoundEventAngry
	"ambient.warped_forest.mood",       // 303 SoundEventAmbientMoodWarpedForest
	"ambient.soulsand_valley.mood",     // 304 SoundEventAmbientMoodSoulsandValley
	"ambient.nether_wastes.mood",       // 305 SoundEventAmbientMoodNetherWastes
	"ambient.basalt_deltas.mood",       // 306 SoundEventAmbientMoodBasaltDeltas
	"ambient.crimson_forest.mood",      // 307 SoundEventAmbientMoodCrimsonForest
	"respawn_anchor.charge",            // 308 SoundEventRespawnAnchorCharge
	"respawn_anchor.deplete",           // 309 SoundEventRespawnAnchorDeplete
	"respawn_anchor.set_spawn",         // 310 SoundEventRespawnAnchorSetSpawn
	"respawn_anchor.ambient",           // 311 SoundEventRespawnAnchorAmbient
	"particle.soul_escape.quiet",       // 312 SoundEventSoulEscapeQuiet
	"particle.soul_escape.loud",        // 313 SoundEventSoulEscapeLoud
	"record.pigstep",                   // 314 SoundEventRecordPigstep
	"lodestone_compass.link_compass_to_lodestone", // 315 SoundEventLinkCompassToLodestone
	"smithing_table.use",                          // 316 SoundEventUseSmithingTable
	"armor.equip_netherite",                       // 317 SoundEventEquipNetherite
	"ambient.warped_forest.loop",                  // 318 SoundEventAmbientLoopWarpedForest
	"ambient.soulsand_valley.loop",                // 319 SoundEventAmbientLoopSoulsandValley
	"ambient.nether_wastes.loop",                  // 320 SoundEventAmbientLoopNetherWastes
	"ambient.basalt_deltas.loop",                  // 321 SoundEventAmbientLoopBasaltDeltas
	"ambient.crimson_forest.loop",                 // 322 SoundEventAmbientLoopCrimsonForest
	"ambient.warped_forest.additions",             // 323 SoundEventAmbientAdditionWarpedForest
	"ambient.soulsand_valley.additions",           // 324 SoundEventAmbientAdditionSoulsandValley
	"ambient.nether_wastes.additions",             // 325 SoundEventAmbientAdditionNetherWastes
	"ambient.basalt_deltas.additions",             // 326 SoundEventAmbientAdditionBasaltDeltas
	"ambient.crimson_forest.additions",            // 327 SoundEventAmbientAdditionCrimsonForest
	"power.on.sculk_sensor",                       // 328 SoundEventSculkSensorPowerOn
	"power.off.sculk_sensor",                      // 329 SoundEventSculkSensorPowerOff
	"bucket.fill.powder_snow",                     // 330 SoundEventBucketFillPowderSnow
	"bucket.empty.powder_snow",                    // 331 SoundEventBucketEmptyPowderSnow
	"cauldron_drip.water.pointed_dripstone",       // 332 SoundEventPointedDripstoneCauldronDripWater
	"cauldron_drip.lava.pointed_dripstone",        // 333 SoundEventPointedDripstoneCauldronDripLava
	"drip.water.pointed_dripstone",                // 334 SoundEventPointedDripstoneDripWater
	"drip.lava.pointed_dripstone",                 // 335 SoundEventPointedDripstoneDripLava
	"pick_berries.cave_vines",                     // 336 SoundEventCaveVinesPickBerries
	"tilt_down.big_dripleaf",                      // 337 SoundEventBigDripleafTiltDown
	"tilt_up.big_dripleaf",                        // 338 SoundEventBigDripleafTiltUp
	"copper.wax.on",                               // 339 SoundEventCopperWaxOn
	"copper.wax.off",                              // 340 SoundEventCopperWaxOff
	"scrape",                                      // 341 SoundEventScrape
	"mob.player.hurt_drown",                       // 342 SoundEventPlayerHurtDrown
	"mob.player.hurt_on_fire",                     // 343 SoundEventPlayerHurtOnFire
	"mob.player.hurt_freeze",                      // 344 SoundEventPlayerHurtFreeze
	"item.spyglass.use",                           // 345 SoundEventUseSpyglass
	"item.spyglass.stop_using",                    // 346 SoundEventStopUsingSpyglass
	"chime.amethyst_block",                        // 347 SoundEventAmethystBlockChime
	"ambient.screamer",                            // 348 SoundEventAmbientScreamer
	"hurt.screamer",                               // 349 SoundEventHurtScreamer
	"death.screamer",                              // 350 SoundEventDeathScreamer
	"milk.screamer",                               // 351 SoundEventMilkScreamer
	"jump_to_block",                               // 352 SoundEventJumpToBlock
	"pre_ram",                                     // 353 SoundEventPreRam
	"pre_ram.screamer",                            // 354 SoundEventPreRamScreamer
	"ram_impact",                                  // 355 SoundEventRamImpact
	"ram_impact.screamer",                         // 356 SoundEventRamImpactScreamer
	"squid.ink_squirt",                            // 357 SoundEventSquidInkSquirt
	"glow_squid.ink_squirt",                       // 358 SoundEventGlowSquidInkSquirt
	"convert_to_stray",                            // 359 SoundEventConvertToStray
	"cake.add_candle",                             // 360 SoundEventCakeAddCandle
	"extinguish.candle",                           // 361 SoundEventExtinguishCandle
	"ambient.candle",                              // 362 SoundEventAmbientCandle
	"block.click",                                 // 363 SoundEventBlockClick
	"block.click.fail",                            // 364 SoundEventBlockClickFail
	"block.sculk_catalyst.bloom",                  // 365 SoundEventSculkCatalystBloom
	"block.sculk_shrieker.shriek",                 // 366 SoundEventSculkShriekerShriek
	"nearby_close",                                // 367 SoundEventWardenNearbyClose
	"nearby_closer",                               // 368 SoundEventWardenNearbyCloser
	"nearby_closest",                              // 369 SoundEventWardenNearbyClosest
	"agitated",                                    // 370 SoundEventWardenSlightlyAngry
	"record.otherside",                            // 371 SoundEventRecordOtherside
	"tongue",                                      // 372 SoundEventTongue
	"irongolem.crack",                             // 373 SoundEventCrackIronGolem
	"irongolem.repair",                            // 374 SoundEventRepairIronGolem
	"listening",                                   // 375 SoundEventListening
	"heartbeat",                                   // 376 SoundEventHeartbeat
	"horn_break",                                  // 377 SoundEventHornBreak
	"",                                            // 378 reserved
	"block.sculk.spread",                          // 379 SoundEventSculkSpread
	"charge.sculk",                                // 380 SoundEventSculkCharge
	"block.sculk_sensor.place",                    // 381 SoundEventSculkSensorPlace
	"block.sculk_shrieker.place",                  // 382 SoundEventSculkShriekerPlace
	"horn_call0",                                  // 383 SoundEventGoatCall0
	"horn_call1",                                  // 384 SoundEventGoatCall1
	"horn_call2",                                  // 385 SoundEventGoatCall2
	"horn_call3",                                  // 386 SoundEventGoatCall3
	"horn_call4",                                  // 387 SoundEventGoatCall4
	"horn_call5",                                  // 388 SoundEventGoatCall5
	"horn_call6",                                  // 389 SoundEventGoatCall6
	"horn_call7",                                  // 390 SoundEventGoatCall7
	"",                                            // 391 reserved
	"",                                            // 392 reserved
	"",                                            // 393 reserved
	"",                                            // 394 reserved
	"",                                            // 395 reserved
	"",                                            // 396 reserved
	"",                                            // 397 reserved
	"",                                            // 398 reserved
	"",                                            // 399 reserved
	"",                                            // 400 reserved
	"",                                            // 401 reserved
	"",                                            // 402 reserved
	"",                                            // 403 reserved
	"",                                            // 404 reserved
	"",                                            // 405 reserved
	"",                                            // 406 reserved
	"",                                            // 407 reserved
	"",                                            // 408 reserved
	"",                                            // 409 reserved
	"",                                            // 410 reserved
	"",                                            // 411 reserved
	"",                                            // 412 reserved
	"",                                            // 413 reserved
	"",                                            // 414 reserved
	"",                                            // 415 reserved
	"",                                            // 416 reserved
	"",                                            // 417 reserved
	"",                                            // 418 reserved
	"",                                            // 419 reserved
	"",                                            // 420 reserved
	"",                                            // 421 reserved
	"",                                            // 422 reserved
	"",                                            // 423 reserved
	"",                                            // 424 reserved
	"",                                            // 425 reserved
	"imitate.warden",                              // 426 SoundEventImitateWarden
	"listening_angry",                             // 427 SoundEventListeningAngry
	"item_given",                                  // 428 SoundEventItemGiven
	"item_taken",                                  // 429 SoundEventItemTaken
	"disappeared",                                 // 430 SoundEventDisappeared
	"reappeared",                                  // 431 SoundEventReappeared
	"drink.milk",                                  // 432 SoundEventDrinkMilk
	"block.frog_spawn.hatch",                      // 433 SoundEventFrogspawnHatched
	"lay_spawn",                                   // 434 SoundEventLaySpawn
	"block.frog_spawn.break",                      // 435 SoundEventFrogspawnBreak
	"sonic_boom",                                  // 436 SoundEventSonicBoom
	"sonic_charge",                                // 437 SoundEventSonicCharge
	"item_thrown",                                 // 438 SoundeventItemThrown
	"record.5",                                    // 439 SoundEventRecord5
	"convert_to_frog",                             // 440 SoundEventConvertToFrog
	"record.playing",                              // 441 SoundEventRecordPlaying
	"block.enchanting_table.use",                  // 442 SoundEventEnchantingTableUse
	"step_sand",                                   // 443 SoundEventStepSand
	"dash_ready",                                  // 444 SoundEventDashReady
	"bundle.drop_contents",                        // 445 SoundEventBundleDropContents
	"bundle.insert",                               // 446 SoundEventBundleInsert
	"bundle.remove_one",                           // 447 SoundEventBundleRemoveOne
	"pressure_plate.click_off",                    // 448 SoundEventPressurePlateClickOff
	"pressure_plate.click_on",                     // 449 SoundEventPressurePlateClickOn
	"button.click_off",                            // 450 SoundEventButtonClickOff
	"button.click_on",                             // 451 SoundEventButtonClickOn
	"door.open",                                   // 452 SoundEventDoorOpen
	"door.close",                                  // 453 SoundEventDoorClose
	"trapdoor.open",                               // 454 SoundEventTrapdoorOpen
	"trapdoor.close",                              // 455 SoundEventTrapdoorClose
	"fence_gate.open",                             // 456 SoundEventFenceGateOpen
	"fence_gate.close",                            // 457 SoundEventFenceGateClose
	"insert",                                      // 458 SoundEventInsert
	"pickup",                                      // 459 SoundEventPickup
	"insert_enchanted",                            // 460 SoundEventInsertEnchanted
	"pickup_enchanted",                            // 461 SoundEventPickupEnchanted
	"brush",                                       // 462 SoundEventBrush
	"brush_completed",                             // 463 SoundEventBrushCompleted
	"shatter_pot",                                 // 464 SoundEventShatterDecoratedPot
	"break_pot",                                   // 465 SoundEventBreakDecoratedPot
	"block.sniffer_egg.crack",                     // 466 SoundEventSnifferEggCrack
	"block.sniffer_egg.hatch",                     // 467 SoundEventSnifferEggHatched
	"block.sign.waxed_interact_fail",              // 468 SoundEventWaxedSignInteractFail
	"record.relic",                                // 469 SoundEventRecordRelic
	"note.bass",                                   // 470 SoundEventBump
	"pumpkin.carve",                               // 471 SoundEventPumpkinCarve
	"mob.husk.convert_to_zombie",                  // 472 SoundEventConvertHuskToZombie
	"mob.pig.death",                               // 473 SoundEventPigDeath
	"mob.hoglin.converted_to_zombified",           // 474 SoundEventHoglinZombified
	"ambient.underwater.enter",                    // 475 SoundEventAmbientUnderwaterEnter
	"ambient.underwater.exit",                     // 476 SoundEventAmbientUnderwaterExit
	"bottle.fill",                                 // 477 SoundEventBottleFill
	"bottle.empty",                                // 478 SoundEventBottleEmpty
	"crafter.craft",                               // 479 SoundEventCrafterCraft
	"crafter.fail",                                // 480 SoundEventCrafterFail
	"block.decorated_pot.insert",                  // 481 SoundEventDecoratedPotInsert
	"block.decorated_pot.insert_fail",             // 482 SoundEventDecoratedPotInsertFail
	"crafter.disable_slot",                        // 483 SoundEventCrafterDisableSlot
	"trial_spawner.open_shutter",                  // 484 SoundEventTrialSpawnerOpenShutter
	"trial_spawner.eject_item",                    // 485 SoundEventTrialSpawnerEjectItem
	"trial_spawner.detect_player",                 // 486 SoundEventTrialSpawnerDetectPlayer
	"trial_spawner.spawn_mob",                     // 487 SoundEventTrialSpawnerSpawnMob
	"trial_spawner.close_shutter",                 // 488 SoundEventTrialSpawnerCloseShutter
	"trial_spawner.ambient",                       // 489 SoundEventTrialSpawnerAmbient
	"block.copper_bulb.turn_on",                   // 490 SoundEventCopperBulbTurnOn
	"block.copper_bulb.turn_off",                  // 491 SoundEventCopperBulbTurnOff
	"ambient.in.air",                              // 492 SoundEventAmbientInAir
	"breeze_wind_charge.burst",                    // 493 SoundEventBreezeWindChargeBurst
	"imitate.breeze",                              // 494 SoundEventImitateBreeze
	"mob.armadillo.brush",                         // 495 SoundEventArmadilloBrush
	"mob.armadillo.scute_drop",                    // 496 SoundEventArmadilloScuteDrop
	"armor.equip_wolf",                            // 497 SoundEventEquipWolf
	"armor.unequip_wolf",                          // 498 SoundEventUnequipWolf
	"reflect",                                     // 499 SoundEventReflect
	"vault.open_shutter",                          // 500 SoundEventVaultOpenShutter
	"vault.close_shutter",                         // 501 SoundEventVaultCloseShutter
	"vault.eject_item",                            // 502 SoundEventVaultEjectItem
	"vault.insert_item",                           // 503 SoundEventVaultInsertItem
	"vault.insert_item_fail",                      // 504 SoundEventVaultInsertItemFail
	"vault.ambient",                               // 505 SoundEventVaultAmbient
	"vault.activate",                              // 506 SoundEventVaultActivate
	"vault.deactivate",                            // 507 SoundEventVaultDeactive
	"hurt.reduced",                                // 508 SoundEventHurtReduced
	"wind_charge.burst",                           // 509 SoundEventWindChargeBurst
	"imitate.bogged",                              // 510 SoundEventImitateBogged
	"armor.crack_wolf",                            // 511 SoundEventWolfArmourCrack
	"armor.break_wolf",                            // 512 SoundEventWolfArmourBreak
	"armor.repair_wolf",                           // 513 SoundEventWolfArmourRepair
	"mace.smash_air",                              // 514 SoundEventMaceSmashAir
	"mace.smash_ground",                           // 515 SoundEventMaceSmashGround
	"trial_spawner.charge_activate",               // 516 SoundEventTrialSpawnerChargeActivate
	"trial_spawner.ambient_ominous",               // 517 SoundEventTrialSpawnerAmbientOminous
	"ominous_item_spawner.spawn_item",             // 518 SoundEventOminiousItemSpawnerSpawnItem
	"ominous_bottle.end_use",                      // 519 SoundEventOminousBottleEndUse
	"mace.heavy_smash_ground",                     // 520 SoundEventMaceHeavySmashGround
	"ominous_item_spawner.spawn_item_begin",       // 521 SoundEventOminousItemSpawnerSpawnItemBegin
	"",                                            // 522 reserved
	"apply_effect.bad_omen",                       // 523 SoundEventApplyEffectBadOmen
	"apply_effect.raid_omen",                      // 524 SoundEventApplyEffectRaidOmen
	"apply_effect.trial_omen",                     // 525 SoundEventApplyEffectTrialOmen
	"ominous_item_spawner.about_to_spawn_item", // 526 SoundEventOminousItemSpawnerAboutToSpawnItem
	"record.creator",               // 527 SoundEventRecordCreator
	"record.creator_music_box",     // 528 SoundEventRecordCreatorMusicBox
	"record.precipice",             // 529 SoundEventRecordPrecipice
	"vault.reject_rewarded_player", // 530 SoundEventVaultRejectRewardedPlayer
	"imitate.drowned",              // 531 SoundEventImitateDrowned
	"bundle.insert_fail",           // 532 SoundEventBundleInsertFailed
}

var soundEventIDs827 = func() map[string]uint32 {
	ids := make(map[string]uint32, len(soundEvents827))
	for id, name := range soundEvents827 {
		if name != "" {
			ids[name] = uint32(id)
		}
	}
	return ids
}()

func marshalLevelSoundEvent(io *wireIO, raw packet.Packet) {
	pk := raw.(*packet.LevelSoundEvent)
	soundID, ok := soundEventIDs827[pk.SoundType]
	if !io.reading && !ok {
		soundID = 186 // SoundEventDefault
	}
	io.Varuint32(&soundID)
	if io.reading {
		if int(soundID) >= len(soundEvents827) || soundEvents827[soundID] == "" {
			io.UnknownEnumOption(soundID, "level sound event type")
			return
		}
		pk.SoundType = soundEvents827[soundID]
	}
	io.Vec3(&pk.Position)
	io.Varint32(&pk.ExtraData)
	io.String(&pk.EntityType)
	io.Bool(&pk.BabyMob)
	io.Bool(&pk.DisableRelativeVolume)
	if io.reading {
		pk.EntityUniqueID = 0
		pk.FireAtPosition = protocol.Optional[mgl32.Vec3]{}
	}
}
